name: readability
description: readability dart implement, Referencing https://github.com/buriy/python-readability
version: 1.0.5
repository: https://github.com/RosenX/readability

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
dependencies:
  html: ^0.15.2

